import * as T from 'three';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
import {accelerate} from './collision.js';
import {clone} from './vendor/utils/SkeletonUtils.js';
const $=s=>document.querySelector(s),canvas=$('#game'),touch=matchMedia('(pointer:coarse)').matches;
let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){throw new Error('WebGL 2 қолдауы қажет. Chrome браузерінен ашып көр.');}
renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene();scene.background=new T.Color('#a8bec3');scene.fog=new T.FogExp2('#adbec1',.008);
const camera=new T.PerspectiveCamera(65,innerWidth/innerHeight,.1,420);camera.position.set(-9,16,70);camera.lookAt(-5,10,20);
scene.add(new T.HemisphereLight('#d5eafa','#676d38',2.4));const sun=new T.DirectionalLight('#fff0c7',3.2);sun.position.set(70,120,40);scene.add(sun);
let terrain,forest,template,clip,player,bots=[],solids=[],ready=false,playing=false,paused=false,finished=false,elapsed=0,kills=0,ammo=30,reserve=180,reloadEnd=0,shotAt=-1,hp=100,armor=50,aim=false,crouch=false,running=false,yaw=0,pitch=.15,vertical=0,jumpOffset=0,zoneRadius=72,quality='high',scale=1,frameAvg=1/50;
const demoCenter=new T.Vector2(-10,32),demoRadius=44;let demoWarnAt=0,room=null,netAction=null,remotePeerId=null,remotePlayer=null,pendingRemoteState=null,netLastSent=0;
let last=performance.now(),hudAt=0,damageUntil=0,hitUntil=0,toastUntil=0,frames=0,frameTime=0,adjustTime=0,hiddenSince=false;
const keys=new Set(),moveStick={x:0,y:0},lookPointers=new Map(),ray=new T.Raycaster(),v1=new T.Vector3(),v2=new T.Vector3(),camTarget=new T.Vector3(),aimPoint=new T.Vector3(),forward=new T.Vector3(),right=new T.Vector3(),zero=new T.Vector2();let firing=false,drag=false,stickId=null;
const playerPos=new T.Vector3(-10,12,55),zoneCenter=new T.Vector2(-10,27),clock=new T.Clock();
const floor=new T.Mesh(new T.PlaneGeometry(1000,1000),new T.MeshLambertMaterial({color:'#61704b'}));floor.rotation.x=-Math.PI/2;floor.position.y=-62;scene.add(floor);
const ring=new T.Mesh(new T.CylinderGeometry(1,1,50,96,1,true),new T.MeshBasicMaterial({color:'#62b9ee',transparent:true,opacity:.10,side:T.DoubleSide,depthWrite:false}));ring.position.set(zoneCenter.x,-1,zoneCenter.y);scene.add(ring);
const ringLine=new T.Mesh(new T.TorusGeometry(1,.002,4,96),new T.MeshBasicMaterial({color:'#8fdbff'}));ringLine.rotation.x=Math.PI/2;ring.add(ringLine);
const tracers=[];for(let i=0;i<10;i++){const geo=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]);const line=new T.Line(geo,new T.LineBasicMaterial({color:'#f9e9a0',transparent:true,opacity:.8}));line.visible=false;scene.add(line);tracers.push({line,until:0});}let tracerIndex=0;
function resize(){renderer.setPixelRatio(Math.min(devicePixelRatio,1.75)*scale);renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}resize();addEventListener('resize',resize);
async function enterGameMode(){if(!touch)return;try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen({navigationUI:'hide'});}catch{}try{if(screen.orientation?.lock)await screen.orientation.lock('landscape');}catch{}}
async function startGame(){await enterGameMode();return initialize();}
function note(text){$('#toast').textContent=text;toastUntil=performance.now()+2300;}
function height(x,z){if(!terrain)return 11;const fx=(x-terrain.minX)/terrain.step,fz=(z-terrain.minZ)/terrain.step,ix=Math.floor(fx),iz=Math.floor(fz);if(ix<0||iz<0||ix>=terrain.w-1||iz>=terrain.h-1)return null;const a=terrain.heights[iz*terrain.w+ix],b=terrain.heights[iz*terrain.w+ix+1],c=terrain.heights[(iz+1)*terrain.w+ix],d=terrain.heights[(iz+1)*terrain.w+ix+1];if([a,b,c,d].some(v=>v===null))return null;const u=fx-ix,v=fz-iz;return (a*(1-u)+b*u)*(1-v)+(c*(1-u)+d*u)*v;}
async function loadModel(name,index){const manifestResponse=await fetch('./assets/manifest.json');if(!manifestResponse.ok)throw new Error('Модель тізімі жүктелмеді');const manifest=await manifestResponse.json(),entry=manifest[name+'-'+quality];let loaded=0;const chunks=[];for(const part of entry.parts){const response=await fetch('./assets/'+part);if(!response.ok)throw new Error(name+' моделін жүктеу мүмкін болмады ('+response.status+')');const reader=response.body.getReader();while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);loaded+=value.length;$('#loadbar').style.width=(index*42+Math.min(.99,loaded/entry.size)*42)+'%';$('#loadText').textContent=(name==='forest'?'Орман картасы':'Кейіпкер')+' · '+(loaded/1048576).toFixed(1)+' / '+(entry.size/1048576).toFixed(1)+' МБ';}}const blob=new Blob(chunks);if(!('DecompressionStream'in window))throw new Error('Браузерді жаңарту қажет: gzip қолдауы жоқ.');const bytes=await new Response(blob.stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();return new GLTFLoader().parseAsync(bytes,'./assets/');}
function tune(root){const maxAniso=renderer.capabilities.getMaxAnisotropy?.()||4;root.traverse(o=>{if(o.isMesh){o.frustumCulled=!o.isSkinnedMesh;o.castShadow=false;o.receiveShadow=false;for(const m of (Array.isArray(o.material)?o.material:[o.material])){if(m.map)m.map.anisotropy=Math.min(maxAniso,quality==='high'?8:4);if(m.transparent&&m.opacity===1){m.transparent=false;m.alphaTest=.45;m.depthWrite=true;}if(quality==='mobile'){m.normalScale?.set(.85,.85);}m.needsUpdate=true;}}});}
function makeActor(pos,isBot=false){const root=new T.Group(),model=clone(template);root.add(model);scene.add(root);const mixer=new T.AnimationMixer(model);const action=clip?mixer.clipAction(clip):null;action?.play();mixer.update(.01);model.updateMatrixWorld(true);model.traverse(o=>{if(o.isMesh&&o.material?.name?.toLowerCase().includes('gloves'))o.removeFromParent();});model.updateMatrixWorld(true);const box=new T.Box3().setFromObject(model,true),size=box.getSize(new T.Vector3());const s=1.8/size.y;model.scale.multiplyScalar(s);model.position.y=-box.min.y*s;root.position.copy(pos);root.rotation.y=Math.PI;const shadow=new T.Mesh(new T.CircleGeometry(.45,16),new T.MeshBasicMaterial({color:'#0d150e',transparent:true,opacity:.28,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.035;root.add(shadow);
const gun=new T.Group(),metal=new T.MeshStandardMaterial({color:isBot?'#665248':'#242c28',roughness:.65});const body=new T.Mesh(new T.BoxGeometry(.11,.12,.58),metal);gun.add(body);const barrel=new T.Mesh(new T.CylinderGeometry(.025,.025,.32,6),metal);barrel.rotation.x=Math.PI/2;barrel.position.z=.4;gun.add(barrel);gun.position.set(-.28,1.12,.25);root.add(gun);
let marker;if(isBot){marker=new T.Mesh(new T.OctahedronGeometry(.13),new T.MeshBasicMaterial({color:'#e8a883'}));marker.position.y=2.08;root.add(marker);}return {root,model,mixer,action,gun,shadow,marker,hp:100,pos:root.position,think:Math.random(),cooldown:1+Math.random()*2,moving:false};}
async function initialize(){if(ready){startRound();return;}$('#start').disabled=true;$('#quality').disabled=true;$('#loading').hidden=false;quality=$('#quality').value==='high'?'high':$('#quality').value==='mobile'?'mobile':((navigator.deviceMemory&&navigator.deviceMemory<4)?'mobile':'high');try{const f=await loadModel('forest',0);forest=f.scene;forest.position.set(-16.088,-161.695,-1.661);tune(forest);scene.add(forest);forest.updateMatrixWorld(true);forest.traverse(o=>{if(o.isMesh&&/Trunk_|Wood_Fence|Wood_Log|Metal_Fence|Tall_Cliff|Broken_Rocks|Sloped_Rock/.test(o.name))solids.push(o);});$('#loadText').textContent='Карта кедергілері дайындалуда…';for(const mesh of solids){accelerate(mesh);await new Promise(requestAnimationFrame);}const t=await fetch('./assets/terrain.json');if(!t.ok)throw new Error('Жер бедері жүктелмеді');terrain=await t.json();const s=await loadModel('soldier',1);template=s.scene;clip=s.animations[0];if(clip){clip=clip.clone();for(const track of clip.tracks){if(/Hips.*position/i.test(track.name)){for(let i=0;i<track.values.length;i+=3){track.values[i]=track.values[0];track.values[i+2]=track.values[2];}}}}tune(template);const broken=[];template.traverse(o=>{if(o.isMesh&&o.material?.name?.toLowerCase().includes('gloves'))broken.push(o);});broken.forEach(o=>o.removeFromParent());player=makeActor(playerPos);ensureRemote();for(const [x,z]of [[-16,24],[15,40],[-28,60],[6,5]])bots.push(makeActor(new T.Vector3(x,height(x,z)??10,z),true));$('#loadText').textContent='Ойын дайындалуда…';$('#loadbar').style.width='95%';if(renderer.compileAsync)await renderer.compileAsync(scene,camera);ready=true;$('#loadbar').style.width='100%';startRound();}catch(e){console.error(e);$('#loadText').textContent='Қате: '+e.message;$('#start').textContent='ҚАЙТА ЖҮКТЕУ';$('#start').disabled=false;$('#start').onclick=()=>location.reload();}}
function resetInput(){keys.clear();moveStick.x=moveStick.y=0;$('#knob').style.transform='';lookPointers.clear();stickId=null;firing=drag=aim=false;}
function startRound(){elapsed=0;kills=0;ammo=30;reserve=180;reloadEnd=0;shotAt=-1;hp=100;armor=50;zoneRadius=72;vertical=jumpOffset=0;yaw=0;pitch=.13;crouch=running=false;finished=paused=false;playing=true;resetInput();player.pos.set(-10,height(-10,55)??11,55);player.root.visible=true;const spawn=[[-16,24],[15,40],[-28,60],[6,5]];bots.forEach((b,i)=>{b.pos.set(spawn[i][0],height(...spawn[i])??11,spawn[i][1]);b.hp=100;b.root.visible=true;b.cooldown=2+i*.8;});$('#menu').hidden=true;$('#pauseMenu').hidden=true;$('#result').hidden=true;$('#hud').hidden=false;$('#touch').classList.add('playing');camera.position.set(player.pos.x,player.pos.y+3,player.pos.z+5);note('Қауіпсіз аймақта қал. 4 ботты жең!');}
function setPaused(value){if(!ready||finished)return;paused=value;resetInput();$('#pauseMenu').hidden=!value;$('#touch').classList.toggle('playing',!value);if(value&&document.pointerLockElement)document.exitPointerLock();}
function endRound(won){finished=true;playing=false;resetInput();$('#resultTitle').textContent=won?'ЖЕҢІС!':'ОПЕРАЦИЯ АЯҚТАЛДЫ';$('#resultText').textContent=`${kills} бот жойылды · ${Math.floor(elapsed/60)}:${String(Math.floor(elapsed%60)).padStart(2,'0')} уақыт`;$('#result').hidden=false;$('#touch').classList.remove('playing');if(document.pointerLockElement)document.exitPointerLock();}
function reload(){if(!playing||paused||reloadEnd||ammo===30)return;if(reserve<=0){note('Қосымша оқ қалмады');return;}reloadEnd=elapsed+1.7;note('Оқталып жатыр…');}
function jump(){if(playing&&!paused&&jumpOffset<=.001&&!crouch)vertical=5.7;}
function damage(n){const absorb=Math.min(armor,n*.55);armor-=absorb;hp=Math.max(0,hp-n+absorb);damageUntil=performance.now()+200;if(hp<=0)endRound(false);}
function beam(from,to,color='#f9e9a0'){const t=tracers[tracerIndex++%tracers.length],a=t.line.geometry.attributes.position;a.setXYZ(0,from.x,from.y,from.z);a.setXYZ(1,to.x,to.y,to.z);a.needsUpdate=true;t.line.geometry.computeBoundingSphere();t.line.material.color.set(color);t.line.visible=true;t.until=elapsed+.065;}
function shoot(){if(!playing||paused||finished||reloadEnd||elapsed-shotAt<.135)return;if(ammo<=0){reload();return;}shotAt=elapsed;ammo--;ray.setFromCamera(zero,camera);let distance=100,hitBot=null;const target=new T.Vector3();for(const b of bots){if(b.hp<=0)continue;const sphere=new T.Sphere(v1.copy(b.pos).add(new T.Vector3(0,1,0)),.66);const hit=ray.ray.intersectSphere(sphere,target);if(hit){const d=camera.position.distanceTo(hit);if(d<distance){distance=d;hitBot=b;}}}ray.far=distance;const block=ray.intersectObjects(solids,false)[0];ray.far=Infinity;if(block&&block.distance<distance){distance=block.distance;hitBot=null;}ray.ray.at(distance,aimPoint);const origin=player.gun.getWorldPosition(v2);beam(origin,aimPoint);if(hitBot){hitBot.hp-=34;hitUntil=performance.now()+160;if(hitBot.hp<=0){hitBot.root.visible=false;kills++;note('Бот жойылды · +30 оқ');reserve+=30;if(kills===bots.length)endRound(true);}}pitch=Math.max(-.6,pitch-.009);}
function canMove(actor,x,z){if(Math.hypot(x-demoCenter.x,z-demoCenter.y)>demoRadius){if(actor===player&&performance.now()>demoWarnAt){demoWarnAt=performance.now()+1800;note('DEMO аймағының шегі');}return false;}const y=height(x,z);if(y===null||Math.abs(y-actor.pos.y)>1.15)return false;const dx=x-actor.pos.x,dz=z-actor.pos.z,d=Math.hypot(dx,dz);if(d>.001){ray.set(v1.set(actor.pos.x,actor.pos.y+.9,actor.pos.z),v2.set(dx/d,0,dz/d));ray.far=d+.3;const hit=ray.intersectObjects(solids,false)[0];ray.far=Infinity;if(hit)return false;}actor.pos.x=x;actor.pos.z=z;actor.pos.y=y;return true;}

function ensureRemote(){if(!remotePeerId||!template||remotePlayer)return;remotePlayer=makeActor(new T.Vector3(-7,height(-7,55)??11,55));remotePlayer.root.visible=playing;const badge=new T.Mesh(new T.OctahedronGeometry(.11),new T.MeshBasicMaterial({color:'#74dfff'}));badge.position.y=2.08;remotePlayer.root.add(badge);}
function applyRemote(dt){if(!remotePlayer||!pendingRemoteState)return;const s=pendingRemoteState;v1.set(Number(s.x)||0,Number(s.y)||0,Number(s.z)||0);remotePlayer.pos.lerp(v1,1-Math.exp(-14*dt));remotePlayer.root.rotation.y=Number.isFinite(s.r)?s.r:remotePlayer.root.rotation.y;remotePlayer.mixer.timeScale=s.m?1.15:0;remotePlayer.mixer.update(dt);remotePlayer.root.visible=playing;}
function sendNetState(now,force=false){if(!netAction||!remotePeerId||!player||(!playing&&!force)||(!force&&now-netLastSent<50))return;netLastSent=now;Promise.resolve(netAction.send({x:player.pos.x,y:player.pos.y,z:player.pos.z,r:player.root.rotation.y,m:player.mixer.timeScale>.05,c:crouch,h:hp},{target:remotePeerId})).catch(()=>{});}
async function setupNetwork(){const online=$('#online');try{const {joinRoom}=await import('https://esm.run/trystero@0.25.4');room=joinRoom({appId:'almas-battleground-demo-v2'},'public-demo-1');netAction=room.makeAction('state');online.textContent='ОНЛАЙН 1/2';room.onPeerJoin=peerId=>{if(remotePeerId&&remotePeerId!==peerId)return;remotePeerId=peerId;ensureRemote();online.textContent='ОНЛАЙН 2/2';note('2-ойыншы қосылды');sendNetState(performance.now(),true);};room.onPeerLeave=peerId=>{if(peerId!==remotePeerId)return;if(remotePlayer){scene.remove(remotePlayer.root);remotePlayer=null;}remotePeerId=null;pendingRemoteState=null;online.textContent='ОНЛАЙН 1/2';note('2-ойыншы шықты');};netAction.onMessage=(data,{peerId})=>{if(!remotePeerId){remotePeerId=peerId;ensureRemote();online.textContent='ОНЛАЙН 2/2';}if(peerId===remotePeerId)pendingRemoteState=data;};}catch(e){online.textContent='OFFLINE';console.warn('P2P offline',e);}}
setupNetwork();

let collisionAccumulator=0;const playerBase=new T.Vector3();
function update(dt){elapsed+=dt;zoneRadius=72-54*Math.min(1,Math.max(0,elapsed-30)/150);ring.scale.set(zoneRadius,1,zoneRadius);if(reloadEnd&&elapsed>=reloadEnd){const n=Math.min(30-ammo,reserve);ammo+=n;reserve-=n;reloadEnd=0;}const outside=Math.hypot(player.pos.x-zoneCenter.x,player.pos.z-zoneCenter.y)>zoneRadius;if(outside)damage(dt*8);if(!playing)return;
let mx=Number(keys.has('KeyD'))-Number(keys.has('KeyA'))+moveStick.x,mz=Number(keys.has('KeyW'))-Number(keys.has('KeyS'))-moveStick.y;const len=Math.hypot(mx,mz);if(len>1){mx/=len;mz/=len;}forward.set(-Math.sin(yaw),0,-Math.cos(yaw));right.set(Math.cos(yaw),0,-Math.sin(yaw));const speed=crouch?1.55:aim?2.1:running||keys.has('ShiftLeft')||keys.has('ShiftRight')?5.5:3.25;playerBase.copy(player.pos);playerBase.y-=jumpOffset;player.pos.y=playerBase.y;const dx=(forward.x*mz+right.x*mx)*speed*dt,dz=(forward.z*mz+right.z*mx)*speed*dt;collisionAccumulator+=dt;if(Math.abs(dx)+Math.abs(dz)>.0001){canMove(player,player.pos.x+dx,player.pos.z+dz);}const moving=Math.hypot(player.pos.x-playerBase.x,player.pos.z-playerBase.z)>.00001;
if(vertical||jumpOffset){vertical-=15*dt;jumpOffset=Math.max(0,jumpOffset+vertical*dt);if(jumpOffset===0)vertical=0;}player.pos.y+=jumpOffset;player.model.scale.y+=( (crouch?player.normalScale*.7:player.normalScale)-player.model.scale.y)*(1-Math.exp(-12*dt));
player.root.rotation.y=Math.PI+yaw;if(moving&&!aim)player.root.rotation.y=Math.atan2(dx,dz);player.mixer.timeScale=moving?(speed/2.2):0;player.mixer.update(dt);player.shadow.position.y=.035-jumpOffset;
for(const b of bots){if(b.hp<=0)continue;b.think-=dt;b.cooldown-=dt;const dist=b.pos.distanceTo(player.pos);const dx=player.pos.x-b.pos.x,dz=player.pos.z-b.pos.z;b.root.rotation.y=Math.atan2(dx,dz);let walking=false;if(b.think<=0){b.think=.14;const outsideBot=Math.hypot(b.pos.x-zoneCenter.x,b.pos.z-zoneCenter.y)>zoneRadius;const tx=outsideBot?zoneCenter.x:player.pos.x,tz=outsideBot?zoneCenter.y:player.pos.z;const distance=Math.hypot(tx-b.pos.x,tz-b.pos.z);if(distance>9||outsideBot){const speed=outsideBot?2:1.2;walking=canMove(b,b.pos.x+(tx-b.pos.x)/distance*speed*.14,b.pos.z+(tz-b.pos.z)/distance*speed*.14);}b.moving=walking;}b.mixer.timeScale=b.moving?.7:0;b.mixer.update(dt);if(dist<45&&b.cooldown<=0){b.cooldown=1.3+Math.random()*1.2;const from=v1.copy(b.pos).add(new T.Vector3(0,1.3,0)),to=v2.copy(player.pos).add(new T.Vector3(0,crouch?.75:1.15,0)),distance=from.distanceTo(to);ray.set(from,to.clone().sub(from).normalize());ray.far=distance;const blocked=ray.intersectObjects(solids,false).length>0;ray.far=Infinity;if(!blocked){beam(from,to,'#ed996c');if(Math.random()<(crouch?.32:.5))damage(7);}}}
applyRemote(dt);const target=camTarget.copy(player.pos).add(v1.set(0,crouch?1:1.45,0));const distance=aim?2.3:4.8;const offset=v2.set(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance+.55,Math.cos(yaw)*Math.cos(pitch)*distance);offset.addScaledVector(right,aim?.48:.65);const desired=target.clone().add(offset);ray.set(target,offset.clone().normalize());ray.far=offset.length();const cameraBlock=ray.intersectObjects(solids,false)[0];ray.far=Infinity;if(cameraBlock)desired.copy(target).addScaledVector(offset.normalize(),Math.max(.7,cameraBlock.distance-.25));const ground=height(desired.x,desired.z);if(ground!==null)desired.y=Math.max(desired.y,ground+.45);camera.position.lerp(desired,1-Math.exp(-15*dt));const look=target.clone().addScaledVector(forward,40);look.y-=Math.sin(pitch)*40;camera.lookAt(look);camera.fov+=( (aim?48:65)-camera.fov)*(1-Math.exp(-12*dt));camera.updateProjectionMatrix();if(firing)shoot();for(const t of tracers)if(t.until<elapsed)t.line.visible=false;
}
function drawMap(){const c=$('#minimap'),ctx=c.getContext('2d'),s=c.width/155,ox=c.width/2-zoneCenter.x*s,oz=c.height/2-zoneCenter.y*s;ctx.fillStyle='#13221ded';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#7f95733a';ctx.lineWidth=1;for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(i*36,0);ctx.lineTo(i*36,180);ctx.moveTo(0,i*36);ctx.lineTo(180,i*36);ctx.stroke();}ctx.strokeStyle='#88cbee';ctx.beginPath();ctx.arc(90,90,zoneRadius*s,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#edaa84';for(const b of bots)if(b.hp>0){ctx.beginPath();ctx.arc(ox+b.pos.x*s,oz+b.pos.z*s,2.6,0,7);ctx.fill();}if(remotePlayer){ctx.fillStyle='#74dfff';ctx.beginPath();ctx.arc(ox+remotePlayer.pos.x*s,oz+remotePlayer.pos.z*s,3,0,7);ctx.fill();}ctx.strokeStyle='#d8ef7660';ctx.beginPath();ctx.arc(ox+demoCenter.x*s,oz+demoCenter.y*s,demoRadius*s,0,Math.PI*2);ctx.stroke();ctx.save();ctx.translate(ox+player.pos.x*s,oz+player.pos.z*s);ctx.rotate(-yaw);ctx.fillStyle='#d8ef76';ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(-4,4);ctx.lineTo(4,4);ctx.closePath();ctx.fill();ctx.restore();}
function hud(now){$('#hpText').textContent=Math.ceil(hp);$('#hpBar').style.width=hp+'%';$('#armor').textContent=Math.ceil(armor);$('#ammo').textContent=ammo;$('#reserve').textContent=reserve;$('#kills').textContent=kills;$('#alive').textContent=bots.filter(b=>b.hp>0).length+(hp>0?1:0)+(remotePlayer?1:0);$('#weaponState').textContent=reloadEnd?'ОҚТАЛУДА…':'R · ОҚТАУ';const sec=Math.max(0,180-elapsed);$('#zoneTime').textContent=Math.floor(sec/60)+':'+String(Math.floor(sec%60)).padStart(2,'0');$('#zone').style.color=Math.hypot(player.pos.x-zoneCenter.x,player.pos.z-zoneCenter.y)>zoneRadius?'#ffa184':'';$('#hitmark').style.opacity=now<hitUntil?1:0;$('#damage').style.opacity=now<damageUntil?.7:0;$('#toast').style.opacity=now<toastUntil?1:0;drawMap();}
function frame(now){requestAnimationFrame(frame);const raw=(now-last)/1000;last=now;if(document.hidden)return;const dt=Math.min(raw,.04);if(playing&&!paused&&!finished){if(player.normalScale===undefined)player.normalScale=player.model.scale.y;update(dt);sendNetState(now);}if(ready&&now-hudAt>100){hud(now);hudAt=now;}renderer.render(scene,camera);if(ready&&!paused){frames++;frameTime+=raw;adjustTime+=raw;frameAvg=frameAvg*.96+Math.min(raw,.1)*.04;if(frameTime>=1){$('#fps').textContent=Math.round(frames/frameTime)+' FPS';frames=frameTime=0;}if(adjustTime>5){adjustTime=0;let next=scale;if(frameAvg>1/34)next=Math.max(.75,scale-.08);else if(frameAvg<1/56)next=Math.min(touch?1.05:1.2,scale+.04);if(Math.abs(next-scale)>.01){scale=next;resize();}}}}
requestAnimationFrame(frame);
$('#start').onclick=startGame;$('#pause').onclick=()=>setPaused(!paused);$('#resume').onclick=()=>setPaused(false);document.querySelectorAll('.restart').forEach(b=>b.onclick=startRound);
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){setPaused(!paused);return;}if(!playing||paused)return;keys.add(e.code);if(e.repeat)return;if(e.code==='KeyR')reload();if(e.code==='Space')jump();if(e.code==='KeyC')crouch=!crouch;});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{resetInput();if(playing)setPaused(true);});document.addEventListener('visibilitychange',()=>{resetInput();if(document.hidden&&playing)setPaused(true);last=performance.now();});
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(touch||!playing||paused)return;if(e.button===2){aim=true;return;}if(document.pointerLockElement===canvas)firing=true;else{drag=true;canvas.setPointerCapture(e.pointerId);canvas.requestPointerLock?.().catch(()=>{});}});addEventListener('pointerup',e=>{if(e.pointerType==='mouse'){firing=drag=false;if(e.button===2)aim=false;}});addEventListener('mousemove',e=>{if(!playing||paused||touch)return;if(document.pointerLockElement===canvas||drag){yaw-=e.movementX*.0025;pitch=T.MathUtils.clamp(pitch+e.movementY*.002,-.6,.85);}});
const stick=$('#stick');function stickMove(e){if(e.pointerId!==stickId)return;const r=stick.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,d=Math.hypot(x,y),f=Math.min(1,42/(d||1));moveStick.x=x*f/42;moveStick.y=y*f/42;$('#knob').style.transform=`translate(${x*f}px,${y*f}px)`;}
stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);});stick.addEventListener('pointermove',stickMove);for(const ev of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(ev,e=>{if(e.pointerId===stickId){stickId=null;moveStick.x=moveStick.y=0;$('#knob').style.transform='';}});
const look=$('#look');look.addEventListener('pointerdown',e=>{look.setPointerCapture(e.pointerId);lookPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});});look.addEventListener('pointermove',e=>{const p=lookPointers.get(e.pointerId);if(!p||paused)return;yaw-=(e.clientX-p.x)*.005;pitch=T.MathUtils.clamp(pitch+(e.clientY-p.y)*.004,-.6,.85);p.x=e.clientX;p.y=e.clientY;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])look.addEventListener(ev,e=>lookPointers.delete(e.pointerId));
const fire=$('#fireBtn');fire.addEventListener('pointerdown',e=>{fire.setPointerCapture(e.pointerId);firing=true;shoot();});for(const ev of ['pointerup','pointercancel','lostpointercapture'])fire.addEventListener(ev,()=>firing=false);$('#reloadBtn').onclick=reload;$('#jumpBtn').onclick=jump;$('#aimBtn').onclick=()=>{aim=!aim;$('#aimBtn').style.borderColor=aim?'#d8ef76':'';};$('#crouchBtn').onclick=()=>{crouch=!crouch;$('#crouchBtn').style.borderColor=crouch?'#d8ef76':'';};$('#runBtn').onclick=()=>{running=!running;$('#runBtn').style.borderColor=running?'#d8ef76':'';};
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();setPaused(true);$('#pauseMenu h2').textContent='Графика тоқтады';$('#pauseMenu p').textContent='Жады жетпеді. Бетті жаңартып, «Жеңіл» сапасын таңда.';$('#resume').textContent='БЕТТІ ЖАҢАРТУ';$('#resume').onclick=()=>location.reload();});
